version: '3'
services:
  web:
    image: django_project
    container_name: django_container
    command: bash -c "gunicorn modelproject.wsgi:application -b 0.0.0.0:8000" # 서버 실행
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media # media가 있으면
    networks:
      - server

  nginx:
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./media:/media # media가 있으면
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - django_container
    networks:
      - server

networks:
  server: